# Twitter Consumer API keys
CONSUMER_KEY = "PUT YOUR CONSUMER KEY HERE"
CONSUMER_KEY_SECRET = "PUT YOUR CONSUMER KEY SECRET HERE"

# Twitter Access tokens
ACCESS_TOKEN = "PUT YOUR ACCESS TOKEN HERE"
ACCESS_TOKEN_SECRET = "PUT YOUR ACCESS TOKEN SECRET HERE"
